Trabalho/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Trabalho.Models;
using Trabalho.DAO;


namespace Trabalho.Controllers
{
    public class CadastroController : Controller
    {
        private readonly ILogger<CadastroController> _logger;

        public CadastroController(ILogger<CadastroController> logger)
        {
            _logger = logger;
        }

        public IActionResult CadastroPessoal()
        {
            return View();
        }

        public IActionResult CadastroFormacao(CurriculoViewModel curriculo)
        {
            return View(curriculo);
        }

        public IActionResult CadastroExpProf(CurriculoViewModel curriculo)
        {
            return View(curriculo);
        }
        public IActionResult CadastroIdiomas(CurriculoViewModel curriculo)
        {
            return View(curriculo);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Edita1(string id)
        {
            try
            {
                CurriculoDAO dao = new CurriculoDAO();
                CurriculoViewModel curriculo = dao.Consulta(id);
                if (curriculo == null)
                    return RedirectToAction("index");
                else
                    return View("CadastroEditarPessoal", curriculo);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }
        public IActionResult Edita2(string id)
        {
            try
            {
                CurriculoDAO dao = new CurriculoDAO();
                CurriculoViewModel curriculo = dao.Consulta(id);
                if (curriculo == null)
                    return RedirectToAction("index");
                else
                    return View("CadastroEditarFormacao", curriculo);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }
        public IActionResult Edita3(string id)
        {
            try
            {
                CurriculoDAO dao = new CurriculoDAO();
                CurriculoViewModel curriculo = dao.Consulta(id);
                if (curriculo == null)
                    return RedirectToAction("index");
                else
                    return View("CadastroEditarExpProf", curriculo);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult Edita4(string id)
        {
            try
            {
                CurriculoDAO dao = new CurriculoDAO();
                CurriculoViewModel curriculo = dao.Consulta(id);
                if (curriculo == null)
                    return RedirectToAction("index");
                else
                    return View("CadastroEditarIdiomas", curriculo);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult Salvar1(CurriculoViewModel curriculo, string id)
        {
            try
            {
                CurriculoDAO dao = new CurriculoDAO();
                
                if (curriculo.cpf == null)
                {
                    curriculo.cpf = id;
                }

               // ValidaDadosPessoal(curriculo.cpf);


                if (curriculo.complementoEnd == null)
                {
                    curriculo.complementoEnd = "";
                }

                if (dao.Consulta(curriculo.cpf) == null)
                {
                    dao.Inserir1(curriculo);
                    CurriculoViewModel Select = dao.Consulta(curriculo.cpf);
                    return RedirectToAction("CadastroFormacao", Select);
                }

                else
                {
                    dao.Alterar1(curriculo);
                    CurriculoViewModel Select = dao.Consulta(curriculo.cpf);
                    return View("CadastroEditarFormacao", Select);
                }  
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }
        public IActionResult Salvar4(CurriculoViewModel curriculo, string id)
        {
            try
            {
                if (curriculo.idioma1 == null)
                {
                    curriculo.idioma1 = "";
                }

                if (curriculo.idioma2 == null)
                {
                    curriculo.idioma2 = "";
                }
                if (curriculo.idioma3 == null)
                {
                    curriculo.idioma3 = "";
                }
           
                CurriculoDAO dao = new CurriculoDAO();
                if (curriculo.cpf == null)
                {
                    curriculo.cpf = id;
                }

                    dao.Inserir4(curriculo);

                return View("CadastroConfirma");
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }
        public IActionResult Salvar3(CurriculoViewModel curriculo, string id)
        {
            try
            {
                if (curriculo.experiencia1Ate == null)
                {
                    curriculo.experiencia1Ate = "";
                }

                if (curriculo.experiencia1Desde == null)
                {
                    curriculo.experiencia1Desde = "";
                }
                if (curriculo.experiencia2Ate == null)
                {
                    curriculo.experiencia2Ate = "";
                }
                if (curriculo.experiencia2Desde == null)
                {
                    curriculo.experiencia2Desde = "";
                }
                if (curriculo.experiencia3Ate == null)
                {
                    curriculo.experiencia3Ate = "";
                }
                if (curriculo.experiencia3Desde == null)
                {
                    curriculo.experiencia3Desde = "";
                }
                if (curriculo.experiencia2 == null)
                {
                    curriculo.experiencia2 = "";
                }
                if (curriculo.experiencia3 == null)
                {
                    curriculo.experiencia3 = "";
                }
                if (curriculo.experiencia1 == null)
                {
                    curriculo.experiencia1 = "";
                }

                CurriculoDAO dao = new CurriculoDAO();
                if (curriculo.cpf == null)
                {
                    curriculo.cpf = id;
                }

                if (dao.Consulta(curriculo.cpf) == null)
                {
                    dao.Inserir3(curriculo);
                    CurriculoViewModel Select = dao.Consulta(id);
                    return View("CadastroIdiomas", Select);
                }

                else
                {
                    dao.Inserir3(curriculo);
                    CurriculoViewModel Select = dao.Consulta(id);
                    return View("CadastroEditarIdiomas", Select);
                }
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }
        public IActionResult Salvar2(CurriculoViewModel curriculo, string id)
        {
            try
            {
                CurriculoDAO dao = new CurriculoDAO();

                if (curriculo.curso1 == null)
                {
                    curriculo.curso1 = "";
                }
                if (curriculo.curso2 == null)
                {
                    curriculo.curso2 = "";
                }
                if (curriculo.curso3 == null)
                {
                    curriculo.curso3 = "";
                }
                if (curriculo.curso4 == null)
                {
                    curriculo.curso4 = "";
                }
                if (curriculo.curso5 == null)
                {
                    curriculo.curso5 = "";
                }
                if (curriculo.cpf == null)
                {
                    curriculo.cpf = id;
                }

                if (dao.Consulta(curriculo.cpf) == null)
                {
                    dao.Inserir2(curriculo);
                    CurriculoViewModel Select = dao.Consulta(id);
                    return View("CadastroEditarExpProf", Select);
                    //return RedirectToAction("CadastroExpProf", curriculo);
                }

                else
                {
                    dao.Inserir2(curriculo);
                    CurriculoViewModel Select = dao.Consulta(id);
                    return View("CadastroEditarExpProf", Select);
                    //return RedirectToAction("CadastroEditarExpProf", curriculo);
                }
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult NovoCurriculo()
        {
            CurriculoViewModel curriculo = new CurriculoViewModel();
            return View("CadastroPessoal", curriculo);
        }

        //private void ValidaDadosPessoal(CurriculoViewModel curriculo, string operacao)
        //{
        //    //Validação das informações pessoais
        //    if (!ValidaCPF(curriculo.cpf))

Trabalho/Views/Cadastro/CadastroConfirma.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<CurriculoViewModel>

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Prototipo</title>
    <link rel="stylesheet" type="text/css" href="~/css/prototipo.css" media="screen" />
</head>

<body>
    <header>
        <nav id="nav-menu">
            <div id="site-name">
                CURRICULUM
                <span>
                    <div class="menu-right">
                        <a asp-area="" asp-controller="Home" asp-action="Index" id="sub-menu"> Menu Inicial</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a asp-area="" asp-controller="Home" asp-action="ListaBD" id="sub-menu">Lista de Currículos</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                    </div>
                </span>
            </div>
        </nav>
    </header>

    <div id="background" class="col-12">
        <div id="under-header">
            <div class="button">
                <img src="~/img/joia2.jpg" alt="Parabéns" class="imgConfirma">
                <div >
                    <span margin: 0px 15px 0px 80px; id="sucessoMensagem"> Parabéns, suas mudanças foram salvas!
                         <h1 class="textoBemMaior">Acesse o <a asp-area="" asp-controller="Home" asp-action="ListaBD" id="sub-menu"> menu </a> e encontre o seu currículo!</h1>
                    </span>
                </div>

                <!--<button asp-area="" asp-controller="Home" asp-action="Index"  id="btnAvancar2" >Avançar</button> -->
               
               
            </div>
            </div>
        </div>

        <div id="rodapé"></div>
    </body>

    </html>

Trabalho/Views/Cadastro/CadastroEditarFormacao.cshtml
@model CurriculoViewModel

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Criar curriculo</title>
    <link rel="stylesheet" type="text/css" href="~/css/prototipo.css" media="screen" />
</head>

<body>

    <header>
        <nav id="nav-menu">
            <div id="site-name">
                CURRICULUM
                <span>
                    <div class="menu-right">
                        <a asp-area="" asp-controller="Home" asp-action="Index" id="sub-menu">Menu Inicial</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                    </div>
                </span>
            </div>
        </nav>
    </header>

    <div id="background">
        <div id="uniaoDivs">

        </div>
        <div id="sub-background">
            <div id="FormFormacao" accept-charset="UTF-8" action="action_page.php" autocomplete="off" target="_blank">
                <form asp-action="Salvar2" asp-route-id="@Model.cpf" method="post">
                    <div>
                        <label class="titleFormacao">CADASTRO DE FORMAÇÃO ACADEMICA E CURSOS</label>
                    </div>
                    <div style="margin: 0 auto; text-align: center; width: 100%">
                        <div style="float: left; margin: 0px 15px 0px 15px; text-align: justify; width: 60%">
                            <div class="semCursos">
                                <h1 class="formacao">
                                    <label for="formacao">Formação: </label>
                                    <select id="formacao" name="formacao" asp-for="formacao">
                                        <option value="Estudante">Estudante</option>
                                        <option value="EMCompleto">Ensino Médio Completo</option>
                                        <option value="EMIncompleto">Ensino Médio Incompleto</option>
                                        <option value="CursandoSuperior">Cursando Ens. Superior</option>
                                        <option value="Sup.Completo">Ens. Superior Completo</option>
                                        <option value="PosGrad">Pós Graduado</option>
                                        <option value="PosIncomp.">Pós Graduação Incompleto</option>
                                    </select>
                                </h1>
                            </div>

                            <h1 class="formacao">
                                <label id="CabecalhoCurso">Cursos</label>
                            </h1>

                            <h1 class="formacao">
                                <label>Curso 1:</label>
                                <input asp-action="" type="text" name="curso1" id="cursos" value="@Model.curso1" title="Digite um curso que você tenha feito (até 5)" required asp-for="curso1"/>
                            </h1>
                            <h1 class="formacao">
                                <label>Curso 2:</label>
                                <input asp-action="" type="text" name="curso2" id="cursos" value="@Model.curso2" title="Digite um curso que você tenha feito (até 5)" asp-for="curso2"/>
                            </h1>
                            <h1 class="formacao">
                                <label>Curso 3:</label>
                                <input asp-action="" type="text" name="curso3" id="cursos" value="@Model.curso3" title="Digite um curso que você tenha feito (até 5)" asp-for="curso3"/>
                            </h1>
                            <h1 class="formacao">
                                <label>Curso 4:</label>
                                <input asp-action="" type="text" name="curso4" id="cursos" value="@Model.curso4" title="Digite um curso que você tenha feito (até 5)" asp-for="curso4"/>
                            </h1>
                            <h1 class="formacao">
                                <label>Curso 5:</label>
                                <input asp-action="" type="text" name="curso5" id="cursos" value="@Model.curso5" title="Digite um curso que você tenha feito (até 5)" asp-for="curso5"/>
                            </h1>
                        </div>
                        <!--=================================================================================================================================================================================================================-->
                        <div style="float: left; margin: 0px 0px 0px 0px; text-align: justify; width: 30%;">
                            <img width="100%" class="ilustrativa1" src="~/img/curriculoex3.jpg">
                            <div class="button">
                                <input type="submit" value="Avançar" class="advanceButton" href="~/Cadastro/Salvar2?id=@Model.cpf"/>
                                <!--<button asp-area="" asp-controller="Cadastro" asp-action="CadastroExpProf" class="advanceButton">
        Avançar
    </button>-->
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    <div id="rodapéForm">

    </div>
</body>

</html>

Trabalho/Views/Cadastro/CadastroEditarPessoal.cshtml
@model CurriculoViewModel
    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Criar curriculo</title>
    <link rel="stylesheet" type="text/css" href="~/css/prototipo.css" media="screen" />
</head>

<body>

    <header>
        <nav id="nav-menu">
            <div id="site-name">
                CURRICULUM
                <span>
                    <div class="menu-right">
                        <a asp-area="" asp-controller="Home" asp-action="Index" id="sub-menu">Menu Inicial</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                    </div>
                </span>
            </div>
        </nav>
    </header>

    <div id="background">
        <div id="uniaoDivs">

        </div>
        <div id="sub-background">
            <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
            <div id="divPessoal" accept-charset="UTF-8" action="action_page.php" autocomplete="off" target="_blank">
                <form asp-action="Salvar1" asp-route-id="@Model.cpf" method="post">
                    <div>
                        <label class="titlePessoal">CADASTRO DE INFORMAÇÕES PESSOAIS</label>
                    </div>
                    <div style="margin: 0 auto; text-align: center; width: 100%">
                        <div style="float: left; margin: 50px 15px 0px 15px; text-align: justify; width: 30%">
                            <h1 class="pessoais">
                                <label class="control-label">Nome: </label>
                                <input name="nome" type="text" value="@Model.nome" class="form-control" required />
                            </h1>

                            <h1 class="pessoais">
                                <label>CPF: </label>
                                <input type="text" name="cpf" \ pattern="\d{11}" placeholder="123456789XX"
                                       required\ title="Digite um CPF no formato: xxxxxxxxxxx" class="form-control" value="@Model.cpf" readonly>
                                <!--  <input id="botao" type="submit" value="Verificar">-->
                            </h1>

                            <h1 class="pessoais">
                                <label>Celular: </label>
                                <input type="text" name="celular" \ pattern= "\[0-9]{2}\[\s][0-9]{4}-[0-9]{4}"
                                       placeholder="11 999999999" title="Digite um celular no formato: 11 999999999" maxlength="12"
                                       required class="form-control" value="@Model.celular">
                                <!-- <input id="botao" type="submit" value="Verificar">-->
                            </h1>

                            <h1 class="pessoais">
                                <label>Email: </label>
                                <input type="email" value="@Model.email" placeholder="name@email.com" required name="email" class="form-control" />
                                <!-- <input id="botao" type="submit" value="Verificar" />-->
                            </h1>

                            <h1 class="pessoais" id="cargo">
                                <label>Cargo Pretendido: </label>
                                <input name="cargoPretendido" type="text" class="form-control" required placeholder="Engenheiro Civil" value="@Model.cargoPretendido" />
                            </h1>

                        </div>
                        <!--=================================================================================================================================================================================================================-->
                        <div style="float: left; margin: 50px 15px 0px 15px; text-align: justify; width: 40%;">
                            <h1 class="pessoais">
                                <label>CEP: </label>
                                <input id="cep" type="text" value="@Model.cep" \ title="Digite um cep no formato: XXXXX-XXX" required
                                       pattern="\d{5}-?\d{3}" class="form-control" name="cep" />
                                <!-- <input id="botao"  type="submit" value="Verificar" />-->
                            </h1>

                            <h1 class="pessoais">
                                <label>Rua </label>
                                <input id="rua" type="text" name="rua" required class="form-control" value="@Model.rua" />
                                <!-- <span asp-validation-for="rua" class="text-danger"></span>-->
                                <!-- <input id="botao" type="submit" value="Verificar" /
                                NAME TEM QUE SER IGUAL A VARIAVEL QUE ESTIVER ENTRANDO>-->
                            </h1>

                            <h1 class="pessoais">
                                <label>Número </label>
                                <input id="numeroEnd" type="number" value="@Model.numeroEnd" required class="form-control" name="numeroEnd" />
                                <!-- <input id="botao" type="submit" value="Verificar" />-->
                            </h1>

                            <h1 class="pessoais">
                                <label>Bairro </label>
                                <input id="bairro" type="text" value="@Model.bairro" required class="form-control" name="bairro" />
                                <!--   <input id="botao" type="submit" value="Verificar" />-->
                            </h1>

                            <h1 class="pessoais">
                                <label>Complemento </label>
                                <input id="complementoEnd" type="text" value="@Model.complementoEnd" class="form-control" name="complementoEnd" />
                                <!--  <input id="botao" type="submit" value="Verificar" />-->
                            </h1>

                            <h1 class="pessoais">
                                <label for="estado">Estado</label>
                                <select id="estado" class="form-control" name="estado" asp-for="estado">
                                    <option value="AC">Acre</option>
                                    <option value="AL">Alagoas</option>
                                    <option value="AP">Amapá</option>
                                    <option value="AM">Amazonas</option>
                                    <option value="BA">Bahia</option>
                                    <option value="CE">Ceará</option>
                                    <option value="DF">Distrito Federal</option>
                                    <option value="ES">Espírito Santo</option>
                                    <option value="GO">Goiás</option>
                                    <option value="MA">Maranhão</option>
                                    <option value="MT">Mato Grosso</option>
                                    <option value="MS">Mato Grosso do Sul</option>
                                    <option value="MG">Minas Gerais</option>
                                    <option value="PA">Pará</option>
                                    <option value="PB">Paraíba</option>
                                    <option value="PR">Paraná</option>
                                    <option value="PE">Pernambuco</option>
                                    <option value="PI">Piauí</option>
                                    <option value="RJ">Rio de Janeiro</option>
                                    <option value="RN">Rio Grande do Norte</option>
                                    <option value="RS">Rio Grande do Sul</option>
                                    <option value="RO">Rondônia</option>
                                    <option value="RR">Roraima</option>
                                    <option value="SC">Santa Catarina</option>
                                    <option value="SP">São Paulo</option>
                                    <option value="SE">Sergipe</option>
                                    <option value="TO">Tocantins</option>
                                </select>
                            </h1>
                        </div>

                        <script type="text/javascript">
                            $("#cep").focusout(function () {
                                //Início do Comando AJAX
                                $.ajax({
                                    //O campo URL diz o caminho de onde virá os dados
                                    //É importante concatenar o valor digitado no CEP
                                    url: 'https://viacep.com.br/ws/' + $(this).val() + '/json/unicode/',
                                    //Aqui você deve preencher o tipo de dados que será lido,
                                    //no caso, estamos lendo JSON.
                                    dataType: 'json',
                                    //SUCESS é referente a função que será executada caso
                                    //ele consiga ler a fonte de dados com sucesso.
                                    //O parâmetro dentro da função se refere ao nome da variável
                                    //que você vai dar para ler esse objeto.
                                    success: function (resposta) {
                                        //Agora basta definir os valores que você deseja preencher
                                        //automaticamente nos campos acima.
                                        $("#rua").val(resposta.logradouro);
                                        //$("#numero").val(resposta.complemento);
                                        $("#bairro").val(resposta.bairro);
                                        $("#cidade").val(resposta.localidade);
                                        $("#uf").val(resposta.uf);
                                        //Vamos incluir para que o Número seja focado automaticamente
                                        //melhorando a experiência do usuário
                                        $("#numero").focus();
                                    }
                                });
                            });
                        </script>
                        <!--=================================================================================================================================================================================================================-->
                        <div style="float: left; margin: 0px 0px 0px 0px; text-align: justify; width: 20%;">
                            <img width="150%" class="ilustrativa1" src="~/img/curriculoex3.jpg">
                            <div class="button">
                                <input type="submit" value="Avançar" class="advanceButton" href="~/Cadastro/Salvar2?id=@Model.cpf"/>
                                <!-- <button type="submit" asp-area="" asp-controller="Cadastro" asp-action="CadastroFormacao" class="advanceButton">
                                        Avançar
                                    </button>-->
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div id="rodapé">

        </div>
    </body>

    </html>